name:                Austerity
version:             0.1.0.0
github:              "githubuser/Austerity"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Austerity#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- groom
- pdf-toolbox-core
- pdf-toolbox-content
- pdf-toolbox-document
- Decimal
- directory
- servant
- servant-server
- servant-lucid
- lucid
- wai
- warp
- hourglass
- http-api-data
- sqlite-simple
- beam-core
- beam-sqlite
- time
- servant-js
- aeson

library:
  source-dirs: 
    - src

executables:
  Austerity-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Austerity

tests:
  Austerity-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Austerity
